name: docs

on:
  # trigger deployment on every push to master branch
  push:
    branches: [master]
  # trigger deployment manually
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # <--- allows to read repo

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all commits to get last updated time or other git info
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.17.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version:  ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm i

      # run build script
      - name: Build Vuepress nav
        run: pnpm run docs:nav -f

      - name: Build Vuepress sit
        run: pnpm run docs:build

      - name: Deploy to Github pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          # deploy to gh-pages
          target_branch: gh-pages
          # deploy the default output dir of vuepress
          build_dir: docs/.vuepress/dist
        env:
          # Add https://github.com/meltdeer/blog/settings/secrets/actions (Repository secrets)
          GITHUB_TOKEN: ${{ secrets.VUEPRESS_TOCKEN }}
          
